# .github/workflows/ci.yml
# replace the whole micromamba step ⬇
- uses: mamba-org/setup-micromamba@v2      # new action 🎉
  with:
    micromamba-version: "2.0.5-0"          # ⬅ any version ≥0.25 works  :contentReference[oaicite:2]{index=2}
    environment-file: env.yml
    environment-name: labauto
    init-shell: bash                       # default is bash; keeps things simple
    cache-environment: true
    cache-downloads: true
