# .github/workflows/ci.yml
name: LabAuto CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    # 1) Checkout source code
    - name: Checkout source
      uses: actions/checkout@v4

    # <<< THE FIX IS HERE >>>
    # 2) Add a step to print the workflow file for debugging
    - name: Debug - Show Workflow File Contents
      run: |
        echo "--- Displaying .github/workflows/ci.yml ---"
        cat .github/workflows/ci.yml
        echo "-------------------------------------------"

    # 3) Setup Micromamba environment, pinning to a specific version
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1.8.0 # Pin to a specific, stable version
      with:
        micromamba-version: "latest"
        environment-file: env.yml
        environment-name: labauto
        init-shell: bash
        cache-environment: true
        cache-downloads: true
        post-cleanup: 'never' # This is the critical line

    # 4) Lint and format check
    - name: Lint and Format Check with Ruff
      shell: bash -l {0}
      run: |
        ruff check .
        ruff format --check .

    # ... (rest of your workflow remains the same)
    - name: Download ClinVar Data
      shell: bash -l {0}
      run: |
        echo "Downloading ClinVar data..."
        wget -q -O clinvar_20250615.vcf.gz https://your-data-hosting.com/path/to/clinvar_20250615.vcf.gz

    - name: Generate Features & Train Model
      shell: bash -l {0}
      run: |
        python scripts/feature_engineering.py clinvar_20250615.vcf.gz
        python scripts/train.py

    - name: Run Tests with Pytest
      shell: bash -l {0}
      run: pytest

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model.pkl