# -------------------------------------------
- uses: mamba-org/setup-micromamba@v2        # 👈 new action
  with:
    micromamba-version: "2.0.5-0"            # any ≥0.25 is fine
    environment-file: env.yml
    environment-name: labauto
    init-shell: bash                         # avoids the zsh deinit path
    cache-environment: true
    cache-downloads:  true
# -------------------------------------------
